[project]
name = "hornets"
version = "0.1.2"
description = "HorNets: Learning from Discrete and Continuous Signals with Routing Neural Networks"
authors = [
    {name = "bkolosk1", email = "bosec99@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scikit-learn>=1.6.1,<2.0.0",
    "torch>=2.8.0",
    "torchvision>=0.22.0",
    "torchaudio>=2.8.0",
    "tqdm>=4.67.1,<5.0.0",
    "numpy>=1.24.0",
    "scipy>=1.17.1",
    "matplotlib>=3.10.8",
    "umap-learn>=0.5.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
